In [1]:
#Start Assignment 1

In [2]:
#Problem Statement1: Write a Python program to multiply a 푀×푁matrix by 푁×퐴matrix and create a real matrix product

import numpy as np
M=int(input("Enter value of M:"))
N=int(input("Enter value of N:"))
A=int(input("Enter value of A:"))

#First matrix(M X N)
mat1=np.array([[0.92825664,0.62790011,0.80130199],[0.64283876,0.16558409,0.54573802],[0.04319311,0.80229079,0.72512472],[0.8005622,0.98844625,0.6982794 ],[0.46600134,0.51451131,0.6415925 ]])
print("First array:")
print(mat1)

#Second matrix(N X A)
mat2=np.array([[0.31898348,0.49050318],[0.53845583,0.48259499],[0.89102055,0.35539951]])
print("Second array:")
print(mat2)

#Matrix Product(Dimension of output matrix = M X A)
print("Dot product of two arrays:")
matprod = np.array(np.dot(mat1,mat2))
print(matprod)

Enter value of M: 5
Enter value of N: 3
Enter value of A: 2


First array:
[[0.92825664 0.62790011 0.80130199]
 [0.64283876 0.16558409 0.54573802]
 [0.04319311 0.80229079 0.72512472]
 [0.8005622  0.98844625 0.6982794 ]
 [0.46600134 0.51451131 0.6415925 ]]
Second array:
[[0.31898348 0.49050318]
 [0.53845583 0.48259499]
 [0.89102055 0.35539951]]
Dot product of two arrays:
[[1.34817155 1.04311662]
 [0.78047845 0.58917953]
 [1.09187707 0.66607684]
 [1.40978206 1.11786567]
 [0.99736045 0.70489738]]


In [3]:
# Problem Statement2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only

import numpy as np
print("Original Array:")
inp_arr=np.array(['Python','PHP','JS','Examples','html5','5'])
print(inp_arr)

dig_arr=np.array([])
for elem in inp_arr:
    chkdig=elem.isdigit()
    if chkdig==0:
        val="False"
    else:
        val="True"
    dig_arr=np.append(dig_arr,[val])
print("Digits only =",np.array(dig_arr))

lowr_arr=np.array([])
for elem in inp_arr:
    chklowr=elem.islower()
    if chklowr==0:
        val="False"
    else:
        val="True"
    lowr_arr=np.append(lowr_arr,[val])
print("Lower cases only =",np.array(lowr_arr))

uppr_arr=np.array([])
for elem in inp_arr:
    chkuppr=elem.isupper()
    if chkuppr==0:
        val="False"
    else:
        val="True"
    uppr_arr=np.append(uppr_arr,[val])
print("Upper cases only =",np.array(uppr_arr))

Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Digits only = ['False' 'False' 'False' 'False' 'False' 'True']
Lower cases only = ['False' 'False' 'False' 'False' 'True' 'False']
Upper cases only = ['False' 'True' 'True' 'False' 'False' 'False']


In [4]:
# Problem Statement3:Write a program thatreads two space-separated positive integers 푋and 푌as input and perform the following tasks:

import numpy as np
X = int(input("Enter value of X:"))
Y = int(input("Enter value of Y:"))
lst1 = np.arange(1,16+(15*(X-1))+1,X) #16 elements with step of X, starting from 1. So last element should be 16+(15 * (X-1)).
print(lst1)
lst2 = np.arange(1,16+(15*(Y-1))+1,Y) #16 elements with step of Y, starting from 1. So last element should be 16+(15 * (Y-1)).
print(lst2)
np1=np.array(lst1)
print(np1)
np2=np.array(lst2)
print(np2)
res_np1=np1.reshape(4,4)
print(res_np1)
res_np2=np2.reshape(4,4)
print(res_np2)
np3=np.array(np.subtract(res_np1,res_np2))
print(np3)
print(np.ravel(np3))

Enter value of X: 7
Enter value of Y: 9


[  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]
[  1  10  19  28  37  46  55  64  73  82  91 100 109 118 127 136]
[  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]
[  1  10  19  28  37  46  55  64  73  82  91 100 109 118 127 136]
[[  1   8  15  22]
 [ 29  36  43  50]
 [ 57  64  71  78]
 [ 85  92  99 106]]
[[  1  10  19  28]
 [ 37  46  55  64]
 [ 73  82  91 100]
 [109 118 127 136]]
[[  0  -2  -4  -6]
 [ -8 -10 -12 -14]
 [-16 -18 -20 -22]
 [-24 -26 -28 -30]]
[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]


In [5]:
# Problem Statement4: Write a Python program that takes two integer-NumPy arrays, 푃and 푄of shape [3∗3]and performthe following task:

import numpy as np
P = np.array([23,56,87,3,6,96,4,6,78])
P = np.reshape(P, (3,3))
print(P)
Q = np.array([12,34,54,7,2,54,6,2,78])
Q = np.reshape(Q, (3,3))
print(Q)
res1=np.array(np.dot(Q,np.subtract(P,Q)))
print(res1)
res2=np.array(np.subtract(P,res1))
print(res2)

[[23 56 87]
 [ 3  6 96]
 [ 4  6 78]]
[[12 34 54]
 [ 7  2 54]
 [ 6  2 78]]
[[-112  616 1824]
 [ -39  378  315]
 [ -98  452  282]]
[[  135  -560 -1737]
 [   42  -372  -219]
 [  102  -446  -204]]
